baseURL = "https://async-mayeul.github.io/"
author = "Fargier Mayeul"
copyright = "Copyright © 2023–2024, Fargier Mayeul and the lee.so; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "paper"
title = "0xl0key"

[params]
  color = 'linen'                           # linen, wheat, gray, light
  github = 'https://github.com/Async-Mayeul'
  avatar = 'https://gravatar.com/mfargier'                 # gravatar email or image url
  name = '0xl0key'
  bio = 'Padawan with weird machines'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://gravatar.com/mfargier'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon